"""Field site profile validation and conversion.

A site profile is the customer-facing deployment contract for field operations:
zones, help points, parking policy, responder groups, devices, and thresholds.
It lets a deployment team change the park map without editing Python code.
"""

from __future__ import annotations

from askme.pipeline.field import customer_project_acceptance as _customer_project_acceptance
from askme.pipeline.field import (
    customer_project_acceptance_registry as _customer_project_acceptance_registry,
)
from askme.pipeline.field import (
    customer_project_artifact_manifests as _customer_project_artifact_manifests,
)
from askme.pipeline.field import customer_project_artifacts as _customer_project_artifacts
from askme.pipeline.field import (
    customer_project_evidence_inventory as _customer_project_evidence_inventory_module,
)
from askme.pipeline.field import (
    customer_project_execution_bindings as _customer_project_execution_bindings,
)
from askme.pipeline.field import (
    customer_project_implementation_handoff as _customer_project_implementation_handoff_module,
)
from askme.pipeline.field import (
    customer_project_managed_objects as _customer_project_managed_objects,
)
from askme.pipeline.field import (
    customer_project_package_assessment as _customer_project_package_assessment,
)
from askme.pipeline.field import (
    customer_project_package_html as _customer_project_package_html,
)
from askme.pipeline.field import (
    customer_project_package_rules as _customer_project_package_rules,
)
from askme.pipeline.field import (
    customer_project_profile_operations as _customer_project_profile_operations,
)
from askme.pipeline.field import customer_project_profiles as _customer_project_profiles
from askme.pipeline.field import (
    customer_project_resource_catalog as _customer_project_resource_catalog,
)
from askme.pipeline.field import customer_project_scope as _customer_project_scope
from askme.pipeline.field import (
    customer_project_template_catalog as _customer_project_template_catalog,
)
from askme.pipeline.field import (
    customer_project_template_delivery as _customer_project_template_delivery,
)
from askme.pipeline.field import (
    customer_project_template_support as _customer_project_template_support,
)
from askme.pipeline.field import delivery_resource_governance as _delivery_resource_governance
from askme.pipeline.field import delivery_resource_registry as _delivery_resource_registry
from askme.pipeline.field import field_site_catalog as _field_site_catalog
from askme.pipeline.field import field_site_runtime_config as _field_site_runtime_config
from askme.pipeline.field import field_site_validation as _field_site_validation
from askme.pipeline.field import solution_delivery_readiness as _solution_delivery_readiness
from askme.pipeline.field.paths import (
    DEFAULT_CUSTOMER_PROJECT_ACCEPTANCE_DOSSIER_ROOT,  # noqa: F401 - public compatibility constant
    DEFAULT_CUSTOMER_PROJECT_PACKAGE_ROOT,  # noqa: F401 - public compatibility constant
    DEFAULT_CUSTOMER_PROJECT_PROPOSAL_ROOT,  # noqa: F401 - public compatibility constant
    DEFAULT_CUSTOMER_PROJECT_TEMPLATE_ROOT,  # noqa: F401 - public compatibility constant
    DEFAULT_DELIVERY_RESOURCE_ROOT,  # noqa: F401 - public compatibility constant
    PROJECT_ROOT,  # noqa: F401 - public compatibility constant
)
from askme.pipeline.field.paths import (
    DEFAULT_SITE_PROFILE_ROOT as DEFAULT_SITE_PROFILE_ROOT,
)

DELIVERY_RESOURCE_GOVERNANCE_DUE_SOON_S = (
    _delivery_resource_registry.DELIVERY_RESOURCE_GOVERNANCE_DUE_SOON_S
)
DELIVERY_RESOURCE_PUBLISH_STATUSES = _delivery_resource_registry.DELIVERY_RESOURCE_PUBLISH_STATUSES
DELIVERY_RESOURCE_TYPES = _delivery_resource_registry.DELIVERY_RESOURCE_TYPES
DEFAULT_DELIVERY_RESOURCE_CATALOG = _delivery_resource_registry.DEFAULT_DELIVERY_RESOURCE_CATALOG
DEFAULT_DELIVERY_RESOURCE_GOVERNANCE_SLA_S = (
    _delivery_resource_registry.DEFAULT_DELIVERY_RESOURCE_GOVERNANCE_SLA_S
)
create_delivery_resource_governance_request = (
    _delivery_resource_governance.create_delivery_resource_governance_request
)
escalate_overdue_delivery_resource_governance_requests = (
    _delivery_resource_governance.escalate_overdue_delivery_resource_governance_requests
)
list_delivery_resource_governance_requests = (
    _delivery_resource_governance.list_delivery_resource_governance_requests
)
review_delivery_resource_governance_request = (
    _delivery_resource_governance.review_delivery_resource_governance_request
)
build_customer_project_resource_catalog = (
    _customer_project_resource_catalog.build_customer_project_resource_catalog
)
customer_project_template_summary_from_items = (
    _customer_project_template_catalog.customer_project_template_summary_from_items
)
list_customer_project_templates = (
    _customer_project_template_catalog.list_customer_project_templates
)
_delivery_resource_catalog = _delivery_resource_registry._delivery_resource_catalog
_delivery_resource_catalog_summary = _delivery_resource_registry._delivery_resource_catalog_summary
_delivery_resource_descriptor = _delivery_resource_registry._delivery_resource_descriptor
_delivery_resource_registry_next_step = _delivery_resource_registry._delivery_resource_registry_next_step
_delivery_resource_registry_path = _delivery_resource_registry._delivery_resource_registry_path
_delivery_resource_registry_summary = _delivery_resource_registry._delivery_resource_registry_summary
_delivery_resource_revision_public_payload = (
    _delivery_resource_registry._delivery_resource_revision_public_payload
)
_delivery_resource_rows = _delivery_resource_registry._delivery_resource_rows
_find_delivery_resource_revision = _delivery_resource_registry._find_delivery_resource_revision
_merge_delivery_resource_catalog = _delivery_resource_registry._merge_delivery_resource_catalog
_read_delivery_resource_revision_file = _delivery_resource_registry._read_delivery_resource_revision_file
_snapshot_delivery_resource_registry_revision = (
    _delivery_resource_registry._snapshot_delivery_resource_registry_revision
)
_write_delivery_resource_registry = _delivery_resource_registry._write_delivery_resource_registry
disable_delivery_resource = _delivery_resource_registry.disable_delivery_resource
list_delivery_resource_registry = _delivery_resource_registry.list_delivery_resource_registry
list_delivery_resource_revisions = _delivery_resource_registry.list_delivery_resource_revisions
load_delivery_resource_registry = _delivery_resource_registry.load_delivery_resource_registry
rollback_delivery_resource_registry = _delivery_resource_registry.rollback_delivery_resource_registry
upsert_delivery_resource = _delivery_resource_registry.upsert_delivery_resource
build_solution_delivery_readiness = (
    _solution_delivery_readiness.build_solution_delivery_readiness
)
_delivery_gate_rollup_status = _solution_delivery_readiness._delivery_gate_rollup_status
_solution_delivery_customer_project_gate = (
    _solution_delivery_readiness._solution_delivery_customer_project_gate
)
_solution_delivery_resource_binding_gate = (
    _solution_delivery_readiness._solution_delivery_resource_binding_gate
)
_solution_delivery_resource_governance_gate = (
    _solution_delivery_readiness._solution_delivery_resource_governance_gate
)
_solution_delivery_template_market_gate = (
    _solution_delivery_readiness._solution_delivery_template_market_gate
)

REQUIRED_RESPONDER_GROUPS = _field_site_validation.REQUIRED_RESPONDER_GROUPS
REQUIRED_DEVICE_SOURCES = _field_site_validation.REQUIRED_DEVICE_SOURCES
DEFAULT_DELIVERY_NAMESPACE = _customer_project_template_support.DEFAULT_DELIVERY_NAMESPACE
TEMPLATE_PUBLISH_STATUSES = _customer_project_template_support.TEMPLATE_PUBLISH_STATUSES
TEMPLATE_RELEASE_REQUEST_STATUSES = (
    _customer_project_template_support.TEMPLATE_RELEASE_REQUEST_STATUSES
)
TEMPLATE_RELEASE_FIELDS = _customer_project_template_support.TEMPLATE_RELEASE_FIELDS
load_field_site_profile = _customer_project_template_support.load_field_site_profile
site_profile_env_references = _customer_project_template_support.site_profile_env_references
_clean_mapping = _customer_project_template_support._clean_mapping
_clean_nested_mapping = _customer_project_template_support._clean_nested_mapping
_dedupe_env_references = _customer_project_template_support._dedupe_env_references
_delivery_namespace = _customer_project_template_support._delivery_namespace
_delivery_tenant_id = _customer_project_template_support._delivery_tenant_id
_env_reference = _customer_project_template_support._env_reference
_find_template_path = _customer_project_template_support._find_template_path
_is_semver = _customer_project_template_support._is_semver
_non_empty_text = _customer_project_template_support._non_empty_text
_sha256_json = _customer_project_template_support._sha256_json
_site_profile_paths = _customer_project_template_support._site_profile_paths
_slug = _customer_project_template_support._slug
_stable_json = _customer_project_template_support._stable_json
_string_list = _customer_project_template_support._string_list
_write_yaml = _customer_project_template_support._write_yaml
_customer_delivery_applicability_scope = (
    _customer_project_template_delivery._customer_delivery_applicability_scope
)
_customer_delivery_dependency_matrix = (
    _customer_project_template_delivery._customer_delivery_dependency_matrix
)
_customer_delivery_out_of_scope = _customer_project_template_delivery._customer_delivery_out_of_scope
_customer_delivery_prerequisites = _customer_project_template_delivery._customer_delivery_prerequisites
_customer_delivery_scenario_acceptance_criteria = (
    _customer_project_template_delivery._customer_delivery_scenario_acceptance_criteria
)
_customer_delivery_surface = _customer_project_template_delivery._customer_delivery_surface
_template_delivery_checklist = _customer_project_template_delivery._template_delivery_checklist
_template_delivery_summary = _customer_project_template_delivery._template_delivery_summary
_template_package_summary = _customer_project_template_delivery._template_package_summary
_unique_template_binding_values = _customer_project_template_delivery._unique_template_binding_values
_unique_template_object_values = _customer_project_template_delivery._unique_template_object_values
_customer_project_implementation_handoff = (
    _customer_project_implementation_handoff_module._customer_project_implementation_handoff
)
_customer_project_acceptance_dossier_manifest = (
    _customer_project_artifact_manifests._customer_project_acceptance_dossier_manifest
)
_customer_project_acceptance_dossier_payload_sha256 = (
    _customer_project_artifact_manifests._customer_project_acceptance_dossier_payload_sha256
)
_customer_project_package_manifest = _customer_project_artifact_manifests._customer_project_package_manifest
_customer_project_package_payload_sha256 = (
    _customer_project_artifact_manifests._customer_project_package_payload_sha256
)
_customer_project_proposal_bundle_payload_sha256 = (
    _customer_project_artifact_manifests._customer_project_proposal_bundle_payload_sha256
)
_customer_project_package_action_plan = (
    _customer_project_package_rules._customer_project_package_action_plan
)
_customer_project_package_delivery_gate = (
    _customer_project_package_rules._customer_project_package_delivery_gate
)
_customer_project_package_import_gate_result = (
    _customer_project_package_rules._customer_project_package_import_gate_result
)
_customer_project_package_acceptance_summary = (
    _customer_project_package_assessment._customer_project_package_acceptance_summary
)
_customer_project_package_reuse_assessment = (
    _customer_project_package_assessment._customer_project_package_reuse_assessment
)
_customer_project_reuse_dependencies = (
    _customer_project_package_assessment._customer_project_reuse_dependencies
)
_managed_object_acceptance_summary = _customer_project_managed_objects._managed_object_acceptance_summary
_managed_object_binding_readiness_summary = (
    _customer_project_managed_objects._managed_object_binding_readiness_summary
)
_ACCEPTANCE_TEST_ALIASES = _customer_project_managed_objects._ACCEPTANCE_TEST_ALIASES
managed_object_catalog_from_site_profile = (
    _customer_project_managed_objects.managed_object_catalog_from_site_profile
)
_acceptance_node_match = _customer_project_managed_objects._acceptance_node_match
_acceptance_resource_bucket = _customer_project_managed_objects._acceptance_resource_bucket
_acceptance_test_check = _customer_project_managed_objects._acceptance_test_check
_delivery_resource_link_status = _customer_project_managed_objects._delivery_resource_link_status
_managed_object_acceptance_status = (
    _customer_project_managed_objects._managed_object_acceptance_status
)
_managed_object_binding_missing_count = (
    _customer_project_managed_objects._managed_object_binding_missing_count
)
_managed_object_binding_payload = _customer_project_managed_objects._managed_object_binding_payload
_managed_object_payload = _customer_project_managed_objects._managed_object_payload
_managed_object_resource_binding_status = (
    _customer_project_managed_objects._managed_object_resource_binding_status
)
build_customer_project_acceptance_registry = (
    _customer_project_acceptance_registry.build_customer_project_acceptance_registry
)
_acceptance_registry_consumers_from_profile = (
    _customer_project_acceptance_registry._acceptance_registry_consumers_from_profile
)
_acceptance_registry_next_step = _customer_project_acceptance_registry._acceptance_registry_next_step
_acceptance_registry_references = _customer_project_acceptance_registry._acceptance_registry_references
_acceptance_registry_status_bucket = (
    _customer_project_acceptance_registry._acceptance_registry_status_bucket
)
_acceptance_registry_summary = _customer_project_acceptance_registry._acceptance_registry_summary
_merge_acceptance_registry_status = (
    _customer_project_acceptance_registry._merge_acceptance_registry_status
)
_SCENARIO_REQUIRED_INPUTS = _customer_project_execution_bindings._SCENARIO_REQUIRED_INPUTS
build_customer_project_execution_bindings = (
    _customer_project_execution_bindings.build_customer_project_execution_bindings
)
_execution_binding_customer_claim = (
    _customer_project_execution_bindings._execution_binding_customer_claim
)
_execution_binding_next_step = _customer_project_execution_bindings._execution_binding_next_step
_execution_binding_summary = _customer_project_execution_bindings._execution_binding_summary
_execution_check_status = _customer_project_execution_bindings._execution_check_status
_execution_resource_ref = _customer_project_execution_bindings._execution_resource_ref
_field_devices_by_source = _customer_project_execution_bindings._field_devices_by_source
_field_ingest_adapter_contract = _customer_project_execution_bindings._field_ingest_adapter_contract
_first_zone_for_object = _customer_project_execution_bindings._first_zone_for_object
_managed_object_bridge_contract = _customer_project_execution_bindings._managed_object_bridge_contract
_managed_object_execution_binding_plan = (
    _customer_project_execution_bindings._managed_object_execution_binding_plan
)
_managed_object_ingest_contract = _customer_project_execution_bindings._managed_object_ingest_contract
_scenario_required_inputs_for_object = (
    _customer_project_execution_bindings._scenario_required_inputs_for_object
)
_sensor_protocol_adapter_name = _customer_project_execution_bindings._sensor_protocol_adapter_name
_sensor_protocol_execution_sources = (
    _customer_project_execution_bindings._sensor_protocol_execution_sources
)
field_operations_config_from_site_profile = (
    _field_site_runtime_config.field_operations_config_from_site_profile
)
render_site_profile_env_template = _field_site_runtime_config.render_site_profile_env_template
_device_registry_entry = _field_site_runtime_config._device_registry_entry
_env_placeholder = _field_site_runtime_config._env_placeholder
_field_threshold_config = _field_site_runtime_config._field_threshold_config
build_customer_project_catalog = _field_site_catalog.build_customer_project_catalog
build_site_profile_catalog = _field_site_catalog.build_site_profile_catalog
build_site_profile_report = _field_site_catalog.build_site_profile_report
_customer_project_delivery_workflow = _field_site_catalog._customer_project_delivery_workflow
_customer_project_summary = _field_site_catalog._customer_project_summary
_site_catalog_next_step = _field_site_catalog._site_catalog_next_step
_site_customer_status = _field_site_catalog._site_customer_status
_site_deployment_stage = _field_site_catalog._site_deployment_stage
_site_profile_catalog_item = _field_site_catalog._site_profile_catalog_item
_site_profile_next_step = _field_site_catalog._site_profile_next_step
validate_field_site_profile = _field_site_validation.validate_field_site_profile
_require_env_reference = _field_site_validation._require_env_reference
_validate_customer_project = _field_site_validation._validate_customer_project
_validate_managed_object_bindings = _field_site_validation._validate_managed_object_bindings
_validate_managed_objects = _field_site_validation._validate_managed_objects
_validate_thresholds = _field_site_validation._validate_thresholds
_zones_by_type = _field_site_validation._zones_by_type
_customer_project_evidence_inventory = (
    _customer_project_evidence_inventory_module._customer_project_evidence_inventory
)
_evidence_file_inventory = _customer_project_evidence_inventory_module._evidence_file_inventory
_evidence_file_modified_at = _customer_project_evidence_inventory_module._evidence_file_modified_at
_evidence_url = _customer_project_evidence_inventory_module._evidence_url
archive_customer_project_profile = _customer_project_profiles.archive_customer_project_profile
customer_project_catalog_acceptance_gate = (
    _customer_project_profiles.customer_project_catalog_acceptance_gate
)
customer_project_catalog_summary_from_projects = (
    _customer_project_profiles.customer_project_catalog_summary_from_projects
)
find_site_profile_path = _customer_project_profiles.find_site_profile_path
list_customer_project_revisions = _customer_project_profiles.list_customer_project_revisions
_append_object_change_log = _customer_project_profiles._append_object_change_log
_customer_project_catalog_delivery_acceptance_gate = (
    _customer_project_profiles._customer_project_catalog_delivery_acceptance_gate
)
_customer_project_catalog_filters = _customer_project_profiles._customer_project_catalog_filters
_customer_project_delivery_status = _customer_project_profiles._customer_project_delivery_status
_customer_payload = _customer_project_profiles._customer_payload
_customer_profile_path = _customer_project_profiles._customer_profile_path
_customer_profile_target = _customer_project_profiles._customer_profile_target
_customer_project_collision_candidates = (
    _customer_project_profiles._customer_project_collision_candidates
)
_customer_project_revision_dir = _customer_project_profiles._customer_project_revision_dir
_customer_project_matches_filters = _customer_project_profiles._customer_project_matches_filters
_customer_project_product_acceptance_gate = (
    _customer_project_profiles._customer_project_product_acceptance_gate
)
_customer_rows = _customer_project_profiles._customer_rows
_delivery_identifier_candidates = _customer_project_profiles._delivery_identifier_candidates
_find_customer_project_profile_path = (
    _customer_project_profiles._find_customer_project_profile_path
)
_find_customer_project_revision = _customer_project_profiles._find_customer_project_revision
_load_customer_project_revisions = _customer_project_profiles._load_customer_project_revisions
_normalize_customer_project_profile = (
    _customer_project_profiles._normalize_customer_project_profile
)
_object_change_log_payload = _customer_project_profiles._object_change_log_payload
_object_change_summary = _customer_project_profiles._object_change_summary
_read_customer_project_revision_file = (
    _customer_project_profiles._read_customer_project_revision_file
)
_revision_public_payload = _customer_project_profiles._revision_public_payload
_snapshot_customer_project_revision = _customer_project_profiles._snapshot_customer_project_revision
_text_filter_matches = _customer_project_profiles._text_filter_matches
_customer_delivery_filename_parts = _customer_project_scope._customer_delivery_filename_parts
_customer_project_profile_diff = _customer_project_scope._customer_project_profile_diff
_delivery_scope_payload = _customer_project_scope._delivery_scope_payload
_delivery_scope_payload_from_customer_site = (
    _customer_project_scope._delivery_scope_payload_from_customer_site
)
_get_nested = _customer_project_scope._get_nested
_same_customer_project_identity = _customer_project_scope._same_customer_project_identity
_same_delivery_project_scope = _customer_project_scope._same_delivery_project_scope
_dossier_evidence_row = _customer_project_package_html._dossier_evidence_row
_dossier_gate_row = _customer_project_package_html._dossier_gate_row
_dossier_workflow_row = _customer_project_package_html._dossier_workflow_row
_h = _customer_project_package_html._h
_metric = _customer_project_package_html._metric
_render_customer_project_acceptance_dossier_html = (
    _customer_project_package_html._render_customer_project_acceptance_dossier_html
)
_render_customer_project_proposal_bundle_html = (
    _customer_project_package_html._render_customer_project_proposal_bundle_html
)
_status_class = _customer_project_package_html._status_class

# Customer acceptance workflow lives in customer_project_acceptance; keep legacy names here.
_FIELD_READINESS_EVIDENCE_DEFAULTS = _customer_project_acceptance._FIELD_READINESS_EVIDENCE_DEFAULTS
ONSITE_ACCEPTANCE_REQUIRED_EVIDENCE_TYPES = _customer_project_acceptance.ONSITE_ACCEPTANCE_REQUIRED_EVIDENCE_TYPES
ONSITE_ACCEPTANCE_EVIDENCE_TYPES = _customer_project_acceptance.ONSITE_ACCEPTANCE_EVIDENCE_TYPES
ONSITE_ACCEPTANCE_STATUSES = _customer_project_acceptance.ONSITE_ACCEPTANCE_STATUSES
ACCEPTANCE_REVIEW_DECISIONS = _customer_project_acceptance.ACCEPTANCE_REVIEW_DECISIONS
CUSTOMER_SIGNOFF_DECISIONS = _customer_project_acceptance.CUSTOMER_SIGNOFF_DECISIONS
list_customer_project_onsite_evidence = _customer_project_acceptance.list_customer_project_onsite_evidence
register_customer_project_onsite_evidence = _customer_project_acceptance.register_customer_project_onsite_evidence
customer_project_acceptance_closure = _customer_project_acceptance.customer_project_acceptance_closure
register_customer_project_acceptance_review = _customer_project_acceptance.register_customer_project_acceptance_review
list_customer_project_customer_signoffs = _customer_project_acceptance.list_customer_project_customer_signoffs
register_customer_project_customer_signoff = _customer_project_acceptance.register_customer_project_customer_signoff
customer_project_acceptance_report = _customer_project_acceptance.customer_project_acceptance_report
_customer_project_launch_readiness = _customer_project_acceptance._customer_project_launch_readiness
_launch_readiness_gate = _customer_project_acceptance._launch_readiness_gate
_customer_project_launch_gate_status = _customer_project_acceptance._customer_project_launch_gate_status
_customer_project_launch_gate_next_step = _customer_project_acceptance._customer_project_launch_gate_next_step
_customer_project_launch_rollup_status = _customer_project_acceptance._customer_project_launch_rollup_status
_execution_binding_report_contracts = _customer_project_acceptance._execution_binding_report_contracts
_customer_project_field_readiness = _customer_project_acceptance._customer_project_field_readiness
_compact_field_readiness = _customer_project_acceptance._compact_field_readiness
_compact_evidence_report = _customer_project_acceptance._compact_evidence_report
_customer_project_raw_onsite_evidence = _customer_project_acceptance._customer_project_raw_onsite_evidence
_customer_project_onsite_evidence_payload = _customer_project_acceptance._customer_project_onsite_evidence_payload
_customer_project_onsite_evidence_payload_from_receipts = _customer_project_acceptance._customer_project_onsite_evidence_payload_from_receipts
_customer_project_auto_onsite_evidence_receipts = _customer_project_acceptance._customer_project_auto_onsite_evidence_receipts
_customer_project_auto_onsite_evidence_receipt = _customer_project_acceptance._customer_project_auto_onsite_evidence_receipt
_customer_project_onsite_evidence_receipts = _customer_project_acceptance._customer_project_onsite_evidence_receipts
_customer_project_onsite_evidence_summary = _customer_project_acceptance._customer_project_onsite_evidence_summary
_customer_project_raw_acceptance_reviews = _customer_project_acceptance._customer_project_raw_acceptance_reviews
_customer_project_acceptance_reviews = _customer_project_acceptance._customer_project_acceptance_reviews
_customer_project_acceptance_review_gate = _customer_project_acceptance._customer_project_acceptance_review_gate
_customer_project_raw_customer_signoffs = _customer_project_acceptance._customer_project_raw_customer_signoffs
_customer_project_customer_signoffs = _customer_project_acceptance._customer_project_customer_signoffs
_customer_project_customer_signoff_gate_snapshot = _customer_project_acceptance._customer_project_customer_signoff_gate_snapshot
_customer_project_customer_signoff_handoff_materials = _customer_project_acceptance._customer_project_customer_signoff_handoff_materials
_customer_project_customer_signoff_payload_sha256 = _customer_project_acceptance._customer_project_customer_signoff_payload_sha256
_customer_project_customer_signoff_gate = _customer_project_acceptance._customer_project_customer_signoff_gate
_customer_project_acceptance_evidence_timeline = _customer_project_acceptance._customer_project_acceptance_evidence_timeline
_customer_project_acceptance_closure_next_step = _customer_project_acceptance._customer_project_acceptance_closure_next_step
_customer_project_latest_proposal_verification = _customer_project_acceptance._customer_project_latest_proposal_verification
_customer_project_latest_audit_export = _customer_project_acceptance._customer_project_latest_audit_export
_recent_json_files = _customer_project_acceptance._recent_json_files
_read_json_file = _customer_project_acceptance._read_json_file
_audit_manifest_matches_scope = _customer_project_acceptance._audit_manifest_matches_scope
_audit_records_hash_matches = _customer_project_acceptance._audit_records_hash_matches
_normalize_onsite_evidence_type = _customer_project_acceptance._normalize_onsite_evidence_type
_normalize_onsite_evidence_status = _customer_project_acceptance._normalize_onsite_evidence_status
_normalize_acceptance_review_decision = _customer_project_acceptance._normalize_acceptance_review_decision
_normalize_customer_signoff_decision = _customer_project_acceptance._normalize_customer_signoff_decision
_normalize_sha256_hex = _customer_project_acceptance._normalize_sha256_hex
_float_value = _customer_project_acceptance._float_value
_customer_project_field_readiness_gates = _customer_project_acceptance._customer_project_field_readiness_gates
_readiness_status = _customer_project_acceptance._readiness_status
_boolean_gate_status = _customer_project_acceptance._boolean_gate_status
_reports_evidence = _customer_project_acceptance._reports_evidence
_customer_project_site_acceptance_checklist = _customer_project_acceptance._customer_project_site_acceptance_checklist
_latest_onsite_receipts_by_type = _customer_project_acceptance._latest_onsite_receipts_by_type
_onsite_acceptance_checklist_item = _customer_project_acceptance._onsite_acceptance_checklist_item
_build_customer_project_acceptance_dossier = _customer_project_acceptance._build_customer_project_acceptance_dossier
_customer_project_acceptance_dossier_verification = _customer_project_acceptance._customer_project_acceptance_dossier_verification
verify_customer_project_proposal_bundle = _customer_project_acceptance.verify_customer_project_proposal_bundle
verify_customer_project_acceptance_dossier = _customer_project_acceptance.verify_customer_project_acceptance_dossier


# Customer project profile/object operations live in customer_project_profile_operations.
create_customer_project_from_template = _customer_project_profile_operations.create_customer_project_from_template
upsert_customer_project_profile = _customer_project_profile_operations.upsert_customer_project_profile
get_customer_project_profile = _customer_project_profile_operations.get_customer_project_profile
upsert_managed_object = _customer_project_profile_operations.upsert_managed_object
delete_managed_object = _customer_project_profile_operations.delete_managed_object
rollback_customer_project_profile = _customer_project_profile_operations.rollback_customer_project_profile


# Customer project artifact import/export flows live in customer_project_artifacts.
export_customer_project_package = _customer_project_artifacts.export_customer_project_package
export_customer_project_acceptance_dossier = (
    _customer_project_artifacts.export_customer_project_acceptance_dossier
)
export_customer_project_proposal_bundle = _customer_project_artifacts.export_customer_project_proposal_bundle
import_customer_project_package = _customer_project_artifacts.import_customer_project_package
verify_customer_project_package = _customer_project_artifacts.verify_customer_project_package
diff_customer_project_package = _customer_project_artifacts.diff_customer_project_package
_utc_timestamp = _customer_project_artifacts._utc_timestamp
_clean_secret = _customer_project_artifacts._clean_secret
_mapping = _customer_project_template_support._mapping

from askme.pipeline.field import (  # noqa: E402
    customer_project_template_release as _customer_project_template_release,
)

create_customer_project_template_release_request = (
    _customer_project_template_release.create_customer_project_template_release_request
)
customer_project_template_release_notes = (
    _customer_project_template_release.customer_project_template_release_notes
)
export_customer_project_template_release_notes_bundle = (
    _customer_project_template_release.export_customer_project_template_release_notes_bundle
)
list_customer_project_template_release_requests = (
    _customer_project_template_release.list_customer_project_template_release_requests
)
list_customer_project_template_revisions = (
    _customer_project_template_release.list_customer_project_template_revisions
)
review_customer_project_template_release_request = (
    _customer_project_template_release.review_customer_project_template_release_request
)
update_customer_project_template_release = (
    _customer_project_template_release.update_customer_project_template_release
)
