"""Static blueprint catalog data."""

from __future__ import annotations

from askme.blueprints.catalog.models import BlueprintSpec

TEXT_MODULES = (
    "llm",
    "tools",
    "memory",
    "mission",
    "cognition",
    "runtime_handoff",
    "pipeline",
    "skill",
    "executor",
    "text",
    "warm_sessions",
    "health",
)

VOICE_MODULES = (
    "llm",
    "tools",
    "memory",
    "mission",
    "cognition",
    "runtime_handoff",
    "pipeline",
    "skill",
    "executor",
    "voice",
    "text",
    "warm_sessions",
    "health",
)

VOICE_PERCEPTION_MODULES = (
    "llm",
    "tools",
    "memory",
    "mission",
    "cognition",
    "runtime_handoff",
    "pipeline",
    "skill",
    "executor",
    "voice",
    "text",
    "warm_sessions",
    "health",
    "pulse",
    "perception",
    "safety",
    "reaction",
)

EDGE_ROBOT_MODULES = (
    "llm",
    "tools",
    "memory",
    "mission",
    "cognition",
    "runtime_handoff",
    "pipeline",
    "skill",
    "executor",
    "voice",
    "text",
    "warm_sessions",
    "health",
    "pulse",
    "perception",
    "safety",
    "reaction",
    "control",
    "led",
    "proactive",
)

MCP_MODULES = (
    "llm",
    "tools",
    "pulse",
    "memory",
    "mission",
    "cognition",
    "runtime_handoff",
    "safety",
    "pipeline",
    "skill",
    "executor",
    "voice",
    "control",
    "warm_sessions",
    "health",
)

LINGTU_VOICE_MODULES = (
    "llm",
    "tools",
    "memory",
    "pipeline",
    "skill",
    "voice",
    "warm_sessions",
    "text",
    "telegram",
)


BLUEPRINTS: tuple[BlueprintSpec, ...] = (
    BlueprintSpec(
        name="text",
        title="文本运营控制台",
        description="面向研发、运营和交付的文本入口，用于知识问答、任务预演和无麦克风调试。",
        import_path="askme.blueprints.presets.text",
        object_name="text",
        startup_command="python -m askme.blueprints.presets.text",
        product_stage="dev_or_ops",
        primary_loop="text",
        customer_visible=False,
        deployment_targets=("developer_laptop", "ops_terminal", "ci_smoke"),
        modules=TEXT_MODULES,
        capabilities=(
            "文本任务输入",
            "知识库检索和证据引用",
            "技能调度",
            "认知规划",
            "fake 或 shadow 运行交接",
            "健康检查和 Dashboard",
        ),
        scenarios=(
            "上传知识并验证回答依据",
            "操作员确认机器人任务草案",
            "无麦克风环境下完成运行交接冒烟测试",
        ),
        required_config=("llm", "memory", "runtime_handoff", "dashboard"),
        external_services=("大模型服务",),
        safety_boundaries=(
            "不依赖麦克风或扬声器。",
            "认知模块和大模型输出不能直接控制硬件。",
            "涉及物理动作的任务仍必须经过运行交接和安全预检。",
        ),
        validation_commands=(
            "python -m pytest tests/test_cognition.py tests/test_text_loop.py -q",
            "python -m askme runtime capabilities --profile text --json",
        ),
        config_aliases={
            "llm": ("brain",),
            "dashboard": ("health_server",),
        },
    ),
    BlueprintSpec(
        name="voice",
        title="语音任务中心",
        description="面向操作员对话、语音任务规划和客户演示的语音入口，不直接接管机器人硬件。",
        import_path="askme.blueprints.presets.voice",
        object_name="voice",
        startup_command="python -m askme.blueprints.presets.voice",
        product_stage="demo_or_lab",
        primary_loop="voice",
        customer_visible=True,
        deployment_targets=("demo_laptop", "lab_pc", "s100p_voice_box"),
        modules=VOICE_MODULES,
        capabilities=(
            "真实麦克风输入",
            "语音识别到认知规划",
            "MiniMax 或项目配置的语音播报",
            "文本兜底输入",
            "操作员确认后进入运行交接",
        ),
        scenarios=(
            "操作员说出巡检 A 区并确认任务计划",
            "访客询问园区知识并获得有依据回答",
            "语音打断、取消和重新确认",
        ),
        required_config=("voice.asr", "voice.tts", "llm", "memory", "dashboard"),
        external_services=("语音识别服务", "大模型服务", "语音合成服务"),
        safety_boundaries=(
            "语音输入可以提出任务请求，但不能直接下发硬件动作。",
            "所有物理任务在交接前都需要明确确认。",
            "实际执行、暂停和中断由运行仲裁器负责。",
        ),
        validation_commands=(
            "python -m askme runtime voice-health --json",
            "python -m pytest tests/test_voice_loop.py tests/test_cognition.py -q",
        ),
        config_aliases={
            "llm": ("brain",),
            "dashboard": ("health_server",),
        },
    ),
    BlueprintSpec(
        name="voice_perception",
        title="语音感知运行时",
        description="在语音任务中心基础上接入场景事实、交互准入、安全状态和主动感知刷新。",
        import_path="askme.blueprints.presets.voice_perception",
        object_name="voice_perception",
        startup_command="python -m askme.blueprints.presets.voice_perception",
        product_stage="lab",
        primary_loop="voice",
        customer_visible=True,
        deployment_targets=("lab_pc_with_camera", "robot_companion_pc"),
        modules=VOICE_PERCEPTION_MODULES,
        capabilities=(
            "语音任务输入",
            "新鲜感知事实同步",
            "交互准入证据",
            "主动感知刷新",
            "安全状态可见",
        ),
        scenarios=(
            "访客在配置的问询点附近发起问路",
            "操作员说“检查这里”时系统先刷新感知",
            "识别到对方并非在和机器人说话时不误答",
        ),
        required_config=("voice", "perception", "interaction_gate", "cognition", "runtime_handoff"),
        external_services=("语音识别服务", "大模型服务", "语音合成服务", "摄像头或感知桥接服务"),
        safety_boundaries=(
            "感知事实只能作为证据，不能作为电机命令。",
            "感知过期时，涉及“这里/那边”的任务必须先刷新。",
            "运行交接前必须展示安全状态。",
        ),
        validation_commands=(
            "python -m pytest tests/test_interaction_gate.py tests/test_active_perception_resolver.py -q",
            "python -m askme runtime capabilities --profile voice --json",
        ),
        config_aliases={
            "interaction_gate": ("voice.interaction_gate",),
        },
    ),
    BlueprintSpec(
        name="edge_robot",
        title="园区巡检机器人运行时",
        description="面向客户试点的边缘运行时，覆盖园区巡检、现场事件、语音交互和机器人侧 IO。",
        import_path="askme.blueprints.presets.edge_robot",
        object_name="edge_robot",
        startup_command="python -m askme.blueprints.presets.edge_robot",
        product_stage="pilot",
        primary_loop="voice",
        customer_visible=True,
        deployment_targets=("robot_edge_pc", "customer_pilot_site", "lab_robot"),
        modules=EDGE_ROBOT_MODULES,
        capabilities=(
            "语音交互",
            "现场事件接入",
            "场景感知",
            "任务运行交接",
            "机器人控制适配",
            "灯光或状态指示",
            "主动巡检和监测",
        ),
        scenarios=(
            "摔倒无法恢复时语音播报并通知保安",
            "卡住或关节电机故障时记录事件",
            "夜间识别窗边或角落陌生人拍照",
            "车辆违停拍照取证",
            "火灾或烟雾告警",
            "垃圾桶满溢巡检",
            "访客问路和带路服务",
            "突发巡检任务打断常规巡检",
        ),
        required_config=(
            "voice",
            "perception",
            "field_operations",
            "runtime_handoff",
            "dingding",
            "robot_control",
        ),
        external_services=(
            "语音识别服务",
            "大模型服务",
            "语音合成服务",
            "钉钉通知 webhook",
            "机器人控制或导航网关",
            "摄像头和传感器桥接服务",
        ),
        safety_boundaries=(
            "大模型和语音层不能直接控制硬件。",
            "现场事件必须通过受控的现场事件入口进入系统。",
            "物理执行由运行仲裁器和安全预检决定。",
            "高风险事件关闭需要受控的主管或操作员审批。",
        ),
        validation_commands=(
            "python -m askme runtime field-readiness --json",
            "python -m pytest tests/test_field_operations.py tests/test_runtime_handoff.py -q",
        ),
        config_aliases={
            "dingding": (
                "field_operations.dingtalk_webhooks",
                "field_operations.dingtalk_security_webhook",
                "field_operations.dingtalk_webhook",
                "alert.dingtalk_webhook",
                "ASKME_DINGTALK_SECURITY_WEBHOOK",
            ),
            "robot_control": (
                "runtime.dog_control",
                "DOG_CONTROL_SERVICE_URL",
            ),
        },
        notes=(
            "这是面向客户试点的主运行蓝图。",
            "是否能声明生产可用，仍取决于现场就绪证据和真实硬件冒烟测试。",
        ),
    ),
    BlueprintSpec(
        name="mcp",
        title="MCP 工具服务",
        description="向 MCP 客户端暴露 askme 工具、资源和受控机器人能力的集成运行时。",
        import_path="askme.blueprints.presets.mcp",
        object_name="mcp",
        startup_command="python -m askme.mcp.server",
        product_stage="integration",
        primary_loop="mcp",
        customer_visible=False,
        deployment_targets=("developer_laptop", "integration_server"),
        modules=MCP_MODULES,
        capabilities=(
            "MCP 工具服务",
            "记忆和技能资源",
            "受控认知规划",
            "运行交接工具接口",
            "按配置接入机器人 API 桥",
        ),
        scenarios=(
            "外部 MCP 客户端查询机器人记忆",
            "外部智能体生成任务草案但不直接下发硬件动作",
            "操作员复核受控工具调用",
        ),
        required_config=("mcp", "tools", "memory", "skills", "runtime_handoff"),
        external_services=("MCP client", "optional robot gateway"),
        safety_boundaries=(
            "MCP 工具必须保留同样的技能准入和运行交接约束。",
            "任何客户端都不能通过该蓝图获得原始电机控制权限。",
        ),
        validation_commands=(
            "python -m askme mcp serve --transport stdio",
            "python -m pytest tests/test_mcp_server.py tests/test_tool_registry_extended.py -q",
        ),
    ),
    BlueprintSpec(
        name="lingtu_voice",
        title="灵途语音导航适配器",
        description="面向灵途导航部署的语音运行时，支持 Telegram 通道，不包含机器人控制平面。",
        import_path="askme.blueprints.presets.lingtu_voice",
        object_name="lingtu_voice",
        startup_command="python -m askme.blueprints.presets.lingtu_voice",
        product_stage="site_specific",
        primary_loop="voice",
        customer_visible=True,
        deployment_targets=("lingtu_navigation_host", "s100p_voice_box"),
        modules=LINGTU_VOICE_MODULES,
        capabilities=(
            "语音导航请求输入",
            "Telegram 操作员通道",
            "知识库问答支持",
            "技能调度到灵途 REST 适配器",
        ),
        scenarios=(
            "访客询问已知目的地",
            "操作员在 Telegram 侧收到服务记录",
            "导航请求被路由到灵途 REST 服务",
        ),
        required_config=("voice", "llm", "telegram", "NAV_GATEWAY_URL"),
        external_services=("灵途导航接口", "Telegram 机器人通道", "语音识别服务", "语音合成服务"),
        safety_boundaries=(
            "不包含机器人控制、安全或灯光模块。",
            "导航权限保留在灵途网关之后。",
        ),
        validation_commands=(
            "python -m askme runtime voice-health --json",
            "python -m pytest tests/test_voice_loop.py -q",
        ),
        config_aliases={
            "llm": ("brain",),
            "NAV_GATEWAY_URL": ("platforms.telegram.lingtu_url",),
        },
        notes=("这是站点定制蓝图，不应作为默认园区巡检运行时对外介绍。",),
    ),
)

ALIASES = {
    "edge": "edge_robot",
    "robot": "edge_robot",
    "park": "edge_robot",
    "voice-plus-perception": "voice_perception",
    "voice_perception": "voice_perception",
    "lingtu": "lingtu_voice",
}
