# Generated by runtime/scripts/generate_runtime_contract_clients.py
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EndpointSpec:
    method: str
    path_template: str
    response_key: str | None = None
    include_idempotency: bool = False

    def path(self, **params: str) -> str:
        if not params:
            return self.path_template
        return self.path_template.format(**params)


class AskmeEdgeVoiceContract:
    HEALTH = EndpointSpec("GET", "/api/v1/health")
    PROCESS_TURN = EndpointSpec(
        "POST",
        "/api/v1/voice/turns",
        include_idempotency=True,
    )
