"""Customer-project package and artifact FastAPI routes."""

from __future__ import annotations

import logging
from collections.abc import Awaitable, Callable
from pathlib import Path
from typing import Any

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, Response

from askme.api.schemas.customer_project_artifacts import (
    CustomerProjectAcceptanceDossierExportResponse,
    CustomerProjectAcceptanceDossierVerifyResponse,
    CustomerProjectPackageDiffResponse,
    CustomerProjectPackageExportResponse,
    CustomerProjectPackageImportResponse,
    CustomerProjectPackageVerifyResponse,
    CustomerProjectProposalBundleExportResponse,
    CustomerProjectProposalBundleVerifyResponse,
)
from askme.pipeline.field.customer_project_artifacts import (
    diff_customer_project_package,
    export_customer_project_acceptance_dossier,
    export_customer_project_package,
    export_customer_project_proposal_bundle,
    import_customer_project_package,
    verify_customer_project_acceptance_dossier,
    verify_customer_project_package,
    verify_customer_project_proposal_bundle,
)

MissionJson = Callable[..., JSONResponse]
OptionalJsonBody = Callable[[Request], Awaitable[dict[str, Any]]]
CorsOptions = Callable[[str], Response]
Authorize = Callable[[Request, dict[str, Any], str], JSONResponse | None]
ProjectReadAuth = Callable[[Request], tuple[JSONResponse | None, dict[str, Any]]]
OperatorProjectScope = Callable[[dict[str, Any]], dict[str, list[str]]]
ScopeAllows = Callable[[dict[str, list[str]], dict[str, Any]], bool]
ScopeItem = Callable[[dict[str, Any]], dict[str, Any]]
ProjectScopeFailure = Callable[[Path, str, dict[str, list[str]]], JSONResponse | None]
PathProvider = Callable[[], Path]
ProjectScopeForbidden = Callable[[], JSONResponse]


def register_customer_project_artifact_routes(
    app: FastAPI,
    *,
    site_profile_root: PathProvider,
    template_root: PathProvider,
    package_output_root: PathProvider,
    acceptance_dossier_output_root: PathProvider,
    proposal_output_root: PathProvider,
    project_read_auth: ProjectReadAuth,
    optional_json_body: OptionalJsonBody,
    authorize: Authorize,
    operator_project_scope: OperatorProjectScope,
    scope_allows: ScopeAllows,
    scope_item_from_package: ScopeItem,
    scope_item_from_proposal: ScopeItem,
    scope_item_from_dossier: ScopeItem,
    scope_item_from_profile: ScopeItem,
    customer_project_scope_failure: ProjectScopeFailure,
    project_scope_forbidden: ProjectScopeForbidden,
    mission_json: MissionJson,
    cors_options_response: CorsOptions,
    logger: logging.Logger,
) -> None:
    """Register customer project package, dossier, and proposal routes."""

    @app.post(
        "/api/field/customer-projects/import",
        tags=["Field Operations"],
        response_model=CustomerProjectPackageImportResponse,
        response_model_exclude_none=True,
    )
    async def field_customer_project_import(request: Request) -> JSONResponse:
        """Import a customer project package generated by the export endpoint."""
        try:
            body = await optional_json_body(request)
            failure = authorize(request, body, "field:project:write")
            if failure is not None:
                return failure
            root = site_profile_root()
            package = body.get("package") if isinstance(body.get("package"), dict) else body
            scope = operator_project_scope(body)
            package_scope = scope_item_from_package({"package": package})
            if not scope_allows(scope, package_scope):
                return project_scope_forbidden()
            result = import_customer_project_package(
                root,
                package,
                overwrite=bool(body.get("overwrite")),
                dry_run=bool(body.get("dry_run")),
                operator_id=str(body.get("operator_id") or ""),
                reason=str(body.get("reason") or ""),
            )
            result.setdefault("package_scope", package_scope)
            result.setdefault("operator_project_scope", scope)
            result = CustomerProjectPackageImportResponse.model_validate(result).model_dump(
                mode="python"
            )
            return mission_json(result, status_code=200 if result.get("accepted") else 422)
        except ValueError as exc:
            return mission_json({"error": str(exc)}, status_code=400)
        except Exception as exc:
            logger.error("Field customer project import endpoint failed: %s", exc)
            return mission_json({"error": str(exc)}, status_code=500)

    @app.post(
        "/api/field/customer-projects/package/verify",
        tags=["Field Operations"],
        response_model=CustomerProjectPackageVerifyResponse,
        response_model_exclude_none=True,
    )
    async def field_customer_project_package_verify(request: Request) -> JSONResponse:
        """Verify a customer project handoff package without writing anything."""
        try:
            body = await optional_json_body(request)
            failure = authorize(request, body, "field:project:read")
            if failure is not None:
                return failure
            package = body.get("package") if isinstance(body.get("package"), dict) else body
            scope = operator_project_scope(body)
            package_scope = scope_item_from_package({"package": package})
            if isinstance(package, dict) and not scope_allows(scope, package_scope):
                return project_scope_forbidden()
            verification = verify_customer_project_package(package)
            payload = CustomerProjectPackageVerifyResponse.model_validate(
                {
                    "accepted": bool(verification.get("valid")),
                    "verification": verification,
                    "package_scope": package_scope,
                    "operator_project_scope": scope,
                }
            ).model_dump(mode="python")
            return mission_json(
                payload,
                status_code=200 if verification.get("valid") else 422,
            )
        except ValueError as exc:
            return mission_json({"error": str(exc)}, status_code=400)
        except Exception as exc:
            logger.error("Field customer project package verify endpoint failed: %s", exc)
            return mission_json({"error": str(exc)}, status_code=500)

    @app.post(
        "/api/field/customer-projects/package/diff",
        tags=["Field Operations"],
        response_model=CustomerProjectPackageDiffResponse,
        response_model_exclude_none=True,
    )
    async def field_customer_project_package_diff(request: Request) -> JSONResponse:
        """Preview how a customer project handoff package would change local profiles."""
        try:
            body = await optional_json_body(request)
            failure = authorize(request, body, "field:project:read")
            if failure is not None:
                return failure
            package = body.get("package") if isinstance(body.get("package"), dict) else body
            scope = operator_project_scope(body)
            package_scope = scope_item_from_package({"package": package})
            if isinstance(package, dict) and not scope_allows(scope, package_scope):
                return project_scope_forbidden()
            verification = verify_customer_project_package(package)
            if not verification.get("valid"):
                payload = CustomerProjectPackageDiffResponse.model_validate(
                    {
                        "accepted": False,
                        "reason": "package_integrity_check_failed",
                        "verification": verification,
                        "package_scope": package_scope,
                        "operator_project_scope": scope,
                    }
                ).model_dump(mode="python")
                return mission_json(
                    payload,
                    status_code=422,
                )
            diff = diff_customer_project_package(site_profile_root(), package)
            incoming_delivery_gate = (
                diff.get("incoming_delivery_gate")
                if isinstance(diff.get("incoming_delivery_gate"), dict)
                else {}
            )
            payload = CustomerProjectPackageDiffResponse.model_validate(
                {
                    "accepted": True,
                    "verification": verification,
                    "diff": diff,
                    "package_scope": package_scope,
                    "operator_project_scope": scope,
                    "would_write": bool(
                        diff.get("change_type") in {"create", "replace"}
                        and incoming_delivery_gate.get("import_allowed", True)
                    ),
                }
            ).model_dump(mode="python")
            return mission_json(payload)
        except ValueError as exc:
            return mission_json({"error": str(exc)}, status_code=400)
        except Exception as exc:
            logger.error("Field customer project package diff endpoint failed: %s", exc)
            return mission_json({"error": str(exc)}, status_code=500)

    @app.post(
        "/api/field/customer-projects/proposal-bundle/verify",
        tags=["Field Operations"],
        response_model=CustomerProjectProposalBundleVerifyResponse,
        response_model_exclude_none=True,
    )
    async def field_customer_project_proposal_bundle_verify(request: Request) -> JSONResponse:
        """Verify a customer project proposal bundle without writing anything."""
        try:
            body = await optional_json_body(request)
            failure = authorize(request, body, "field:project:read")
            if failure is not None:
                return failure
            proposal = body.get("proposal") if isinstance(body.get("proposal"), dict) else body
            scope = operator_project_scope(body)
            if isinstance(proposal, dict) and not scope_allows(
                scope,
                scope_item_from_proposal(proposal),
            ):
                return project_scope_forbidden()
            verification = verify_customer_project_proposal_bundle(proposal)
            payload = CustomerProjectProposalBundleVerifyResponse.model_validate(
                {
                    "accepted": bool(verification.get("valid")),
                    "verification": verification,
                    "proposal_scope": scope_item_from_proposal(proposal),
                }
            ).model_dump(mode="python")
            return mission_json(
                payload,
                status_code=200 if verification.get("valid") else 422,
            )
        except ValueError as exc:
            return mission_json({"error": str(exc)}, status_code=400)
        except Exception as exc:
            logger.error("Field customer project proposal bundle verify endpoint failed: %s", exc)
            return mission_json({"error": str(exc)}, status_code=500)

    @app.post(
        "/api/field/customer-projects/acceptance-dossier/verify",
        tags=["Field Operations"],
        response_model=CustomerProjectAcceptanceDossierVerifyResponse,
        response_model_exclude_none=True,
    )
    async def field_customer_project_acceptance_dossier_verify(request: Request) -> JSONResponse:
        """Verify a customer project acceptance dossier without writing anything."""
        try:
            body = await optional_json_body(request)
            failure = authorize(request, body, "field:project:read")
            if failure is not None:
                return failure
            dossier = body.get("dossier") if isinstance(body.get("dossier"), dict) else body
            scope = operator_project_scope(body)
            dossier_scope = scope_item_from_dossier({"dossier": dossier})
            if isinstance(dossier, dict) and not scope_allows(scope, dossier_scope):
                return project_scope_forbidden()
            verification = verify_customer_project_acceptance_dossier(dossier)
            payload = CustomerProjectAcceptanceDossierVerifyResponse.model_validate(
                {
                    "accepted": bool(verification.get("valid")),
                    "verification": verification,
                    "dossier_scope": dossier_scope,
                }
            ).model_dump(mode="python")
            return mission_json(
                payload,
                status_code=200 if verification.get("valid") else 422,
            )
        except ValueError as exc:
            return mission_json({"error": str(exc)}, status_code=400)
        except Exception as exc:
            logger.error("Field customer project acceptance dossier verify endpoint failed: %s", exc)
            return mission_json({"error": str(exc)}, status_code=500)

    @app.get(
        "/api/field/customer-projects/{identifier}/export",
        tags=["Field Operations"],
        response_model=CustomerProjectPackageExportResponse,
        response_model_exclude_none=True,
    )
    async def field_customer_project_export(identifier: str, request: Request) -> JSONResponse:
        """Export a reusable customer project handoff package."""
        try:
            failure, auth_body = project_read_auth(request)
            if failure is not None:
                return failure
            scope = operator_project_scope(auth_body)
            root = site_profile_root()
            scope_failure = customer_project_scope_failure(root, identifier, scope)
            if scope_failure is not None:
                return scope_failure
            result = export_customer_project_package(
                root,
                identifier,
                output_root=package_output_root(),
            )
            if result.get("accepted") and not scope_allows(scope, scope_item_from_package(result)):
                return project_scope_forbidden()
            if result.get("accepted"):
                result = CustomerProjectPackageExportResponse.model_validate(
                    result
                ).model_dump(mode="python")
            return mission_json(result, status_code=200 if result.get("accepted") else 404)
        except Exception as exc:
            logger.error("Field customer project export endpoint failed: %s", exc)
            return mission_json({"error": str(exc)}, status_code=500)

    @app.get(
        "/api/field/customer-projects/{identifier}/acceptance-dossier",
        tags=["Field Operations"],
        response_model=CustomerProjectAcceptanceDossierExportResponse,
        response_model_exclude_none=True,
    )
    async def field_customer_project_acceptance_dossier(
        identifier: str,
        request: Request,
        check_env: bool = True,
    ) -> JSONResponse:
        """Export a tamper-evident customer acceptance dossier."""
        try:
            failure, auth_body = project_read_auth(request)
            if failure is not None:
                return failure
            scope = operator_project_scope(auth_body)
            root = site_profile_root()
            scope_failure = customer_project_scope_failure(root, identifier, scope)
            if scope_failure is not None:
                return scope_failure
            result = export_customer_project_acceptance_dossier(
                root,
                identifier,
                output_root=acceptance_dossier_output_root(),
                check_env=check_env,
            )
            if result.get("accepted") and not scope_allows(scope, scope_item_from_dossier(result)):
                return project_scope_forbidden()
            if result.get("accepted"):
                result = CustomerProjectAcceptanceDossierExportResponse.model_validate(
                    result
                ).model_dump(mode="python")
            return mission_json(result, status_code=200 if result.get("accepted") else 404)
        except Exception as exc:
            logger.error("Field customer project acceptance dossier endpoint failed: %s", exc)
            return mission_json({"error": str(exc)}, status_code=500)

    @app.get(
        "/api/field/customer-projects/{identifier}/proposal-bundle",
        tags=["Field Operations"],
        response_model=CustomerProjectProposalBundleExportResponse,
        response_model_exclude_none=True,
    )
    async def field_customer_project_proposal_bundle(
        identifier: str,
        request: Request,
        check_env: bool = True,
    ) -> JSONResponse:
        """Export a customer-facing proposal bundle bound to one project."""
        try:
            failure, auth_body = project_read_auth(request)
            if failure is not None:
                return failure
            scope = operator_project_scope(auth_body)
            root = site_profile_root()
            scope_failure = customer_project_scope_failure(root, identifier, scope)
            if scope_failure is not None:
                return scope_failure
            result = export_customer_project_proposal_bundle(
                root,
                template_root(),
                identifier,
                output_root=proposal_output_root(),
                package_output_root=package_output_root(),
                dossier_output_root=acceptance_dossier_output_root(),
                check_env=check_env,
            )
            proposal = result.get("proposal") if isinstance(result.get("proposal"), dict) else {}
            if result.get("accepted") and not scope_allows(scope, scope_item_from_profile(proposal)):
                return project_scope_forbidden()
            if result.get("accepted"):
                result = CustomerProjectProposalBundleExportResponse.model_validate(
                    result
                ).model_dump(mode="python")
            return mission_json(result, status_code=200 if result.get("accepted") else 404)
        except Exception as exc:
            logger.error("Field customer project proposal bundle endpoint failed: %s", exc)
            return mission_json({"error": str(exc)}, status_code=500)

    @app.options("/api/field/customer-projects/import", include_in_schema=False)
    async def field_customer_project_import_cors() -> Response:
        return cors_options_response("POST, OPTIONS")

    @app.options("/api/field/customer-projects/package/verify", include_in_schema=False)
    async def field_customer_project_package_verify_cors() -> Response:
        return cors_options_response("POST, OPTIONS")

    @app.options("/api/field/customer-projects/package/diff", include_in_schema=False)
    async def field_customer_project_package_diff_cors() -> Response:
        return cors_options_response("POST, OPTIONS")

    @app.options("/api/field/customer-projects/proposal-bundle/verify", include_in_schema=False)
    async def field_customer_project_proposal_bundle_verify_cors() -> Response:
        return cors_options_response("POST, OPTIONS")

    @app.options("/api/field/customer-projects/acceptance-dossier/verify", include_in_schema=False)
    async def field_customer_project_acceptance_dossier_verify_cors() -> Response:
        return cors_options_response("POST, OPTIONS")

    @app.options("/api/field/customer-projects/{identifier}/export", include_in_schema=False)
    async def field_customer_project_export_cors(identifier: str) -> Response:
        _ = identifier
        return cors_options_response("GET, OPTIONS")

    @app.options("/api/field/customer-projects/{identifier}/acceptance-dossier", include_in_schema=False)
    async def field_customer_project_acceptance_dossier_cors(identifier: str) -> Response:
        _ = identifier
        return cors_options_response("GET, OPTIONS")

    @app.options("/api/field/customer-projects/{identifier}/proposal-bundle", include_in_schema=False)
    async def field_customer_project_proposal_bundle_cors(identifier: str) -> Response:
        _ = identifier
        return cors_options_response("GET, OPTIONS")


__all__ = ["register_customer_project_artifact_routes"]
